"""add_crons_table

Revision ID: baa02a5d050f
Revises: a1b2c3d4e5f6
Create Date: 2026-04-13 20:14:23.864628

"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "baa02a5d050f"
down_revision = "a1b2c3d4e5f6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "crons",
        sa.Column("cron_id", sa.Text(), server_default=sa.text("public.uuid_generate_v4()::text"), nullable=False),
        sa.Column("assistant_id", sa.Text(), nullable=False),
        sa.Column("thread_id", sa.Text(), nullable=True),
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("schedule", sa.Text(), nullable=False),
        sa.Column(
            "payload", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False
        ),
        sa.Column(
            "metadata", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False
        ),
        sa.Column("on_run_completed", sa.Text(), nullable=True),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("end_time", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("next_run_date", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["assistant_id"], ["assistant.assistant_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["thread_id"], ["thread.thread_id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("cron_id"),
    )
    op.create_index("idx_cron_assistant_id", "crons", ["assistant_id"], unique=False)
    op.create_index("idx_cron_next_run", "crons", ["enabled", "next_run_date"], unique=False)
    op.create_index("idx_cron_thread_id", "crons", ["thread_id"], unique=False)
    op.create_index("idx_cron_user", "crons", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_cron_user", table_name="crons")
    op.drop_index("idx_cron_thread_id", table_name="crons")
    op.drop_index("idx_cron_next_run", table_name="crons")
    op.drop_index("idx_cron_assistant_id", table_name="crons")
    op.drop_table("crons")
    # ### end Alembic commands ###
